IPDapp/urls.py
from django.urls import path
from IPDapp import views
urlpatterns=[
    path('bed_allotment', views.bed_allotment,name='bed_allotment'),
    path('ward-type',views.ward_type_view,name='wt'),
    path('ward-cate',views.ward_cate_view,name='wc'),

#     Master Level Url Like Room Definition......
    path('wing-master',views.wing_master_view,name='wm'),
    path('floor-master',views.floor_master_view,name='fm'),
    path('room-master',views.room_master_view,name='rm'),
    path('bed-master',views.bed_master_view,name='bm'),
    path('bed-master-next',views.bed_master_next_view,name='bmn'),
    path('ward-type',views.ward_t_view,name='wt'),
    path('ward-category',views.ward_c_view,name='wc'),
    path('ward-name',views.ward_name_view,name='wn'),
    path('bed-location',views.bed_location_view,name='bl'),
    path('nursing-station-counter',views.nursing_station_counter_view,name='nsv'),
    path('department',views.depatment_view,name='dpt'),
    path('room-defination',views.room_defination,name='rd'),
    path('ajax-load-room',views.load_room_master,name='ajax_room_m_urls'),
    path('ajax-load-bed',views.load_bed_master,name='ajax_bed_master'),
    path('ajax-load-ward_type',views.load_ward_type_master,name='ajax_ward_type_master'),
    path('ajax-load-ward_cat',views.load_ward_cat_master,name='ajax_ward_cat_master'),
    path('ajax-load-bed_next',views.load_bed_master_next,name='load_bed_master_next'),

#     Django DropDown URL
    path('add/',views.person_create_view,name='person_add'),
    path('country/',views.country_view,name='country'),
    path('city/',views.city_view,name='city'),
    path('<int:pk>/',views.person_update_view,name='person_change'),
    path('ajax/load-cities/',views.load_cities,name='ajax_load_cities')#ajax

]

OpdManagement/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('master_admin/', admin.site.urls),
    path('',include('testapp.urls')),
    path('ipd/',include('IPDapp.urls')),
    path('api/',include('testapp.api.urls')),
    path('api-func/',include('testapp.func_api.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('usermanagementapp/',include('usermanagementapp.urls')),
    path('auto/',include('ramapp.urls')),
    # path('__debug__/', include('debug_toolbar.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

IPDapp/models.py
from django.db import models
from testapp.models import *
# Create your models here.
class BedAllotments(models.Model):
    bed_id=models.CharField(max_length=20,unique=True,null=False,blank=False)
    room_nos=models.ForeignKey('testapp.RoomNumber',on_delete=models.CASCADE)
    bed_nos=models.CharField(max_length=20,unique=True,null=False,blank=False)
    def __str__(self):
        return str(self.bed_nos)
class Department(models.Model):
    department_name=models.CharField(max_length=100,unique=True,null=False,blank=False)
    description=models.TextField(blank=True,null=True)
    def __str__(self):
        return self.department_name

class Ipd_Dept(models.Model):
    department_name=models.CharField(max_length=100,unique=True,null=False,blank=False)
    description=models.TextField(blank=True,null=True)
    def __str__(self):
        return self.department_name

class WardName(models.Model):
    ward_name=models.CharField(max_length=100,unique=True,null=False,blank=False)
    description=models.TextField(blank=True,null=True)
    def __str__(self):
        return self.ward_name
class WingMaster(models.Model):
    wing_name=models.CharField(max_length=100,unique=True,null=False,blank=False)
    description=models.TextField(blank=True,null=True)
    description = models.TextField(blank=True, null=True)
    def __str__(self):
        return self.wing_name
class FloorMaster(models.Model):
    wing_name=models.ForeignKey(WingMaster,on_delete=models.CASCADE)
    floor_name=models.CharField(max_length=100,unique=True,null=False,blank=False)
    description=models.TextField(blank=True,null=True)
    description = models.TextField(blank=True, null=True)
    def __str__(self):
        return self.floor_name
class RoomMaster(models.Model):
    wing_name=models.ForeignKey(WingMaster,on_delete=models.CASCADE)
    floor_name=models.ForeignKey(FloorMaster,on_delete=models.CASCADE)
    room_number=models.CharField(max_length=40)
    description = models.TextField(blank=True, null=True)
    def __str__(self):
        return self.room_number

class AdmissionWardType(models.Model):
    floor_name=models.ForeignKey(FloorMaster,on_delete=models.CASCADE)
    room_number=models.ForeignKey(RoomMaster,on_delete=models.CASCADE)
    ward_type=models.CharField(max_length=100,unique=True,)
    description=models.TextField(blank=True,null=True)
    def __str__(self):
        return self.ward_type

class AdmissionWardCate(models.Model):
    floor_name=models.ForeignKey(FloorMaster,on_delete=models.CASCADE)
    room_number=models.ForeignKey(RoomMaster,on_delete=models.CASCADE)
    ward_type=models.ForeignKey(AdmissionWardType,on_delete=models.CASCADE)
    category_name=models.CharField(max_length=100,unique=True)
    description=models.TextField(blank=True,null=True)
    def __str__(self):
        return self.category_name

class BedMaster(models.Model):
    BED_LOCATION=(
        ('WINDOWS SIDE','WINDOWS SIDE'),
        ('CENTER','CENTER'),
        ('LEFT SIDE','LEFT SIDE'),
        ('RIGHT SIDE','RIGHT SIDE'),
    )
    wing_name = models.ForeignKey(WingMaster, on_delete=models.CASCADE)
    floor_name = models.ForeignKey(FloorMaster, on_delete=models.CASCADE)
    room_number = models.ForeignKey(RoomMaster,on_delete=models.CASCADE)
    bed_no=models.CharField(max_length=30)
    ward_type=models.ForeignKey(AdmissionWardType,on_delete=models.CASCADE)
    ward_category=models.ForeignKey(AdmissionWardCate,on_delete=models.CASCADE)
    bed_location=models.CharField(max_length=100,choices=BED_LOCATION)
    description=models.TextField(blank=True,null=True)
    def __str__(self):
        return str(self.bed_no)
class BedMasterMain(models.Model):
    status=(
        ('Active','Active'),
        ('Inactive','Inactive'),
        ('Occupied','Occupied'),
        ('Un-occupied','Un-occupied'),
    )
    wing_name = models.CharField(max_length=40)
    floor_name = models.CharField(max_length=40)
    room_number = models.CharField(max_length=40)
    bed_no = models.CharField(max_length=30)
    ward_type = models.CharField(max_length=40)
    ward_category = models.CharField(max_length=40)
    bed_location = models.CharField(max_length=40)
    status=models.CharField(max_length=100,choices=status,default='Active')
    description = models.TextField(blank=True, null=True)
    def __str__(self):
        return str(self.bed_no)
class BedLocation(models.Model):
    location_name=models.CharField(max_length=100,unique=True,null=False,blank=False)
    description = models.TextField(blank=True, null=True)
class NursingStationCounter(models.Model):
    counter_name=models.CharField(max_length=100,unique=True,null=False,blank=False)
    inactive=models.BooleanField()
    description = models.TextField(blank=True, null=True)
    def __str__(self):
        return self.counter_name
class Room_Defination(models.Model):
    GENDER=(('MALE','MALE'),('FEMALE','FEMALE'))
    ward_type=models.ForeignKey(AdmissionWardType,on_delete=models.CASCADE,related_name='wardtype')
    ward_name=models.ForeignKey(WardName,on_delete=models.CASCADE,related_name='wardname')
    ward_cate=models.ForeignKey(AdmissionWardCate,on_delete=models.CASCADE,related_name='wardcate')
    wing=models.ForeignKey(WingMaster,on_delete=models.CASCADE,related_name='wing')
    floor=models.ForeignKey(FloorMaster,on_delete=models.CASCADE,related_name='floor')
    department=models.ForeignKey('testapp.RoomNumber',on_delete=models.CASCADE,related_name='department')
    nursing_counter=models.ForeignKey(NursingStationCounter,on_delete=models.CASCADE,related_name='nursecounter')
    room_no=models.ForeignKey('testapp.RoomNumber',on_delete=models.CASCADE,related_name='room')
    Gender=models.CharField(max_length=20,choices=GENDER)
    bed_charge_not_applicable=models.BooleanField()
    inactive=models.BooleanField()
class AdmissionWardCategory(models.Model):
    ward_type=models.ForeignKey(AdmissionWardType,on_delete=models.CASCADE)
    ward_category=models.CharField(max_length=100,unique=True)
    description=models.TextField(blank=True,null=True)
    def __str__(self):
        return self.ward_category
class AdmissionInfos(models.Model):
    ADMISSION_TYPE=(
        ('Normal Admission','Normal Admission'),
        ('Emergency Admission','Emergency Admission'),
        ('Online Admission','Online Admission'),
        ('Offline Admission','Offline Admission'),
    )
    uhid=models.CharField(max_length=50)
    admission_ID=models.CharField(max_length=100)
    admission_datetime=models.DateTimeField(auto_now_add=True,editable=False)
    admission_type=models.CharField(max_length=50,choices=ADMISSION_TYPE)
    req_ward_type=models.ForeignKey(AdmissionWardType,on_delete=models.CASCADE,blank=True,null=True)
    req_ward_cate=models.ForeignKey(AdmissionWardCate,on_delete=models.CASCADE,blank=True,null=True)
    infected=models.BooleanField()
    MLC=models.BooleanField()
    MLC_No=models.CharField(max_length=50,blank=True,null=True)#
    primary_doctor=models.ForeignKey('testapp.DoctorTable',on_delete=models.CASCADE,related_name='primary_doctor',blank=True,null=True)
    department=models.ForeignKey(Ipd_Dept,on_delete=models.CASCADE,related_name='department',blank=True,null=True)
    secondary_doctor=models.ForeignKey('testapp.DoctorTable',on_delete=models.CASCADE,blank=False,null=False,related_name='secoundry_doctor')
    ref_hospital=models.ForeignKey('testapp.HospitalMaster',on_delete=models.CASCADE,blank=True,null=True)
    bed_no=models.ForeignKey(BedMasterMain,on_delete=models.CASCADE,blank=True)
    status=models.CharField(max_length=100,default='admitted',blank=True)


class Bed_Transfer(models.Model):
    uhid=models.CharField(max_length=50)
    admission_ID=models.CharField(max_length=100)
    bed_transfer_id=models.CharField(max_length=50, blank=True,null=True)
    from_ward_type=models.ForeignKey(AdmissionWardType,on_delete=models.CASCADE,related_name='from_ward_type')
    from_ward_cat=models.ForeignKey(AdmissionWardCate,on_delete=models.CASCADE,related_name='from_ward_type')
    from_bed_no=models.ForeignKey(BedMasterMain,on_delete=models.CASCADE,related_name='from_bed_no')
    to_ward_type=models.ForeignKey(AdmissionWardType,on_delete=models.CASCADE,related_name='to_ward_type')
    to_ward_cat=models.ForeignKey(AdmissionWardCate,on_delete=models.CASCADE,related_name='to_ward_type')
    to_bed_no=models.ForeignKey(BedMasterMain,on_delete=models.CASCADE,related_name='to_bed_no')
    transfer_datatime=models.DateTimeField(auto_now_add=True, blank=True)

class Doctor_Transfer(models.Model):
    uhid=models.CharField(max_length=50)
    admission_ID=models.CharField(max_length=100, blank=True,null=True)
    doctor_transfer_id=models.CharField(max_length=50)
    from_doctor=models.ForeignKey('testapp.DoctorTable',on_delete=models.CASCADE,related_name='from_dept')
    from_department=models.ForeignKey(Ipd_Dept,on_delete=models.CASCADE,related_name='from_doctor')
    to_doctor=models.ForeignKey('testapp.DoctorTable',on_delete=models.CASCADE,related_name='to_dept')
    to_department=models.ForeignKey(Ipd_Dept,on_delete=models.CASCADE,related_name='to_doctor')
    transfer_datatime=models.DateField(default=datetime.now)



# ============================DropDownChaining===========================
# Simple Country State Master In Django
class Country(models.Model):
    name=models.CharField(max_length=30)
    def __str__(self):
        return self.name
class City(models.Model):
    country=models.ForeignKey(Country,on_delete=models.CASCADE)
    name=models.CharField(max_length=30)
    def __str__(self):
        return self.name
class Person(models.Model):
    Name=models.CharField(max_length=30)
    country=models.ForeignKey(Country,on_delete=models.SET_NULL,blank=True,null=True)
    city=models.ForeignKey(City,on_delete=models.SET_NULL,blank=True,null=True)
    def __str__(self):
        return self.name

templates/Reports/bed_charge_slip.html
{% extends 'clinical/base.html' %}
{% load static %}
{% block body_block %}
<div class="page-wrapper">
    <div class="content">
        <div class="card" style="padding: 30;">
            <h2>Bed Charge Slip</h2>
            <div class="container-fluid">
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12 col-sm-8 col-xs-8"><br>
                        <div class="card">
                            <div class="header">
                                <div class="body">
                                    <br>
 
                                    <div class="table-responsive">
                                        <table class="datatable table table-stripped ">
    
                                            <thead>
                                                <tr style="background:#d1dae6;">
                                                    <th>S.No</th>
                                                    <th>UHID</th>
                                                    <th>Patient Name</th>
                                                    <th>Age/Gender</th>
                                                    <th>Date Of Birth</th>
                                                  </tr>
                                                  </thead>
                                                  <tbody>
                                                   {% for data in records %}
                                                   <tr>
                                                    <td>{{forloop.counter}}</td>
                                                     <td><a href="/bed_charge_slip_details/{{data.uhid}}">{{data.uhid}}</a></td>
                                                     <td>{{data.title}}.{{data.first_name}}&nbsp;{{data.middle_name}}&nbsp;{{data.last_name}}</td>
                                                     <td>{{data.gender}}</td>
                                                     <td>{{data.dob}}</td>
                                                   </tr>
                                                   {% endfor %}
                                            </tbody>
    
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

templates/Reports/bed_charge_slip_details.html
{% extends 'clinical/base.html' %}
{% load static %}
{% block body_block %}
<div class="page-wrapper">
    <div class="content">
        <div class="card" style="padding: 30;">
            <h2>Bed Charge Slip</h2>
            <div class="container-fluid">
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12 col-sm-8 col-xs-8"><br>
                        <div class="card">
                            <div class="header">
                                <div class="body">
                                    <br>
                                    <div class="icon-button-demo">&nbsp;
                                        <button type="button" class="btn btn-warning" data-toggle="modal"
                                            data-target=".bd-example-modal-xl"><i class="fas fa-plus">Add</i></button>&nbsp;
                                        <a href="/bed_charge_slip_details_edit/{{uhid}}" class="btn btn-info"> <i class="fas fa-edit"
                                                style="color:white;">Edit</i></a>&nbsp;
                                      
                                        <button type="button" class="btn btn-primary" onClick="window.location.reload();">
                                            <i class="fas fa-sync-alt">Refresh</i></button>&nbsp;
                                        <a href="/bed_charge_slip" class="btn btn-danger"> <i class="fas fa-times-circle">Exit</i></a>
    
                                    </div><br>
                                    <div class="table-responsive">
                                        <table class="datatable table table-stripped ">
    
                                            <thead>
                                                <tr style="background:#d1dae6;">
                                                    <th>S.No</th>
                                                    <th>UHID</th>
                                                    <th>ward_type</th>
                                                    <th>ward_cat</th>
                                                    <th>bed_no</th>
                                                    <th>bed_charge</th>
                                                    <th>datetime</th>
                                                  </tr>
                                                  </thead>
                                                  <tbody>
                                                   {% for data in records %}
                                                   <tr>
                                                    <td>{{forloop.counter}}</td>
                                                     <td>{{data.uhid}}</a></td>
                                                     <td>{{data.ward_type}}</td>
                                                     <td>{{data.ward_cat}}</td>
                                                     <td>{{data.bed_no}}</td>
                                                     <td>{{data.bed_charge}}</td>
                                                     <td>{{data.datetime}}</td>
                                                   </tr>
                                                   {% endfor %}
                                            </tbody>
    
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
    <!-- Add Modal -->

    <div class="modal fade bd-example-modal-xl" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <!-- Header -->
            <div class="modal-header" style="background: skyblue;">
                <h5 class="modal-title" id="exampleModalLabel"><b>Bed Charge slip</b></h5>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div><br>
            <!-- Main block -->
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="body" style="border:0px solid red;">
                        <div class="demo-masked-input">
                            <div class="row clearfix">
                                <form method="POST" id="form_id" data-cities-url="{% url 'charge_slip_load' %}">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="form-group col-md-6 mb-0">
                                            <label for="">Ward Type</label>
                                            <select class="custom-select mr-sm-2" id="ward_name" name="ward_name" required>
                                                <option selected>Choose...</option>
                                                {% for data in ward_type_records %}
                                            <option value="{{data.ward_type}}">{{data.ward_type}}</option>
                                            {% endfor %}
                                            </select>
                                        </div>
                                        <div class="form-group col-md-6 mb-0">
                                            <label for="">Ward Category</label>
                                            <select class="custom-select mr-sm-2" id="ward_cat" name="ward_cat" required>
                                                <option selected>Choose...</option>
                                                 {% for data in ward_cat_records %}
                                                <option value="{{data.category_name}}">{{data.category_name}}</option>

                                                {% endfor %}
                                            </select>
                                        </div><br>
                                    </div><br><br>
                                    <div class="row">
                                        <div class="form-group col-md-3 mb-0">
                                            <label for="">Bed Number</label>
                                        </div>
                                        <div class="form-group col-md-6 mb-0">
                                            <select class="custom-select mr-sm-2" id="id_to_bed_no" name="id_to_bed_no" required>
                                                <option selected>Choose...</option>
                                                
                                            </select>
                                        </div>
                                    </div><br><br>
                                    <div class="row">
                                        <div class="form-group col-md-3 mb-0">
                                            <label for="">Bed Charge</label>
                                        </div>
                                        <div class="form-group col-md-6 mb-0">
                                            <input type="number" class="form-control" name="charge_slip" id="charge_slip" required>
                                        </div>
                                    </div><br><br>
                                    <div class="row">
                                        <div class="form-group col-md-3 mb-0">
                                            <label for="">Date</label>
                                        </div>
                                        <div class="form-group col-md-6 mb-0">
                                            <input type="datetime-local" class="form-control" name="date_time" id="date_time" value="{{date_time}}" required>
                                        </div>
                                    </div>
                                        <br><br>
                                    <button type="submit" class="btn btn-success"> <i
                                            class="fas fa-save">&nbsp;Save</i></button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  $("#ward_name").change(function () {
      const ward_type_id = $(this).val();
      const url = $("#form_id").attr("data-cities-url");  
  
      $.ajax({             
          url: url,   
          data: {
              'ward_type_id':ward_type_id 
          },
          success: function (data) { 
              $("#ward_cat").html(data);  
              let html_data = '<option value="">---------</option>';
              data.forEach(function (cat) {
              console.log(cat)
                  html_data += `<option value="${cat.category_name}">${cat.category_name}</option>`
              });
              console.log(html_data);
              $("#ward_cat").html(html_data);
  
  
          }
      });
  
  });
  </script>
  <script>
    $("#ward_cat").change(function () {
        const ward_cat_id = $(this).val();
        const ward_type_id = $("#ward_name").val(); 
        const url = $("#form_id").attr("data-cities-url");  
    
        $.ajax({             
            url: url,   
            data: {
                'ward_type_id':ward_type_id,
                'ward_cat_id':ward_cat_id 
            },
            success: function (data) { 
                $("#id_to_bed_no").html(data);  
                let html_data = '<option value="">---------</option>';
                data.forEach(function (bed_no) {
                console.log(bed_no)
                    html_data += `<option value="${bed_no.bed_no}">${bed_no.bed_no}</option>`
                });
                console.log(html_data);
                $("#id_to_bed_no").html(html_data);
    
    
            }
        });
    
    });
    </script>
{% endblock %}

templates/Reports/discharge_report.html
{% extends 'clinical/base.html' %}
{% load static %}
{% block body_block %}
<style>
 
    /* .form-control{
        border-radius: 15px;
    } */
</style>
<!--Main Content-->
<div class="page-wrapper">
    <div class="content">
        <div class="card">
            <div class="card-body">
                <h2>Discharge Reports</h2><br>
                <form method="POST">
                    {% csrf_token %}
                    <div class="row filter-row">
                        <div class="col-md-2">
                            <div class="form-group ">
                                <label class="focus-label">Start Date</label>
                                <input type="date" class="form-control" name="start_date">
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group ">
                                <label class="focus-label">End Date</label>
                                <input type="date" class="form-control" name="end_date">
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label class="focus-label">Primary Doctor</label>
                                <select name="doctor_name" id="doctor_name" class="form-control">
                                    <option value=''>----selete----</option>
                                    {% for data in doctor_records %}
                                    <option value="{{data.doctor_id}}">{{data.doctor_name}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class=" col-md-2">
                            <div class="form-group ">
                                <label class="focus-label">Ward category</label>
                                <select name="ward_type" id="ward_type" class="form-control">
                                    <option value=''>----selete----</option>
                                    {% for data in ward_type_records %}
                                    <option value="{{data.id}}">{{data.ward_type}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <div class="form-group">
                                <label>Ward Type</label>
                                <select name="ward_cat" id="ward_cat" class="form-control">
                                    <option value=''>----selete----</option>
                                    {% for data in ward_cat_records %}
                                    <option value="{{data.id}}">{{data.category_name}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-2">
                            <input type="submit" class="form-control btn btn-info" placeholder="Last name"
                                value="Search">

                        </div>
                        <div class=" col-md-2">
                            <a href="/reports" class="form-control btn btn-primary" style="background-color:#006778">Go
                                Back</a>
                        </div>
                    </div>

                </form>

                </form>
            </div>

        </div>
        <div class="card" style="padding: 30px; ">
            <table class="datatable table table-stripped">
                <thead>
                    <th>S.No</th>
                    <th>Name</th>
                    <th>Admission Datetime</th>
                    <th>Discharge Datetime</th>
                    <th>Status</th>
                    <th>Ward type</th>
                    <th>ward cat</th>
                    <th>bed_no</th>

                </thead>
                <tbody>
                    {% for dis,pat,ad,type,cat,bed in records %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{pat.first_name}}</td>
                        <td>{{ad.admission_datetime}}</td>
                        <td>{{dis.discharge_datetime}}</td>
                        <td>{{dis.status}}</td>
                        <td>{{type}}</td>
                        <td>{{cat}}</td>
                        <td>{{bed}}</td>
                    </tr>
                    {% endfor %}

                </tbody>

            </table>
        </div>
    </div>
</div>

{% endblock %}